spring.application.name=pchouse-pdf-api
server.port=4999
pom.version=@project.version@
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.mvc.async.request-timeout=-1
server.tomcat.connection-timeout=-1
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false
logging.level.pt.*=OFF
client.allowIps=127.0.0.1,192.168.1.0/24,::1
report.basedir=
task.executor.core.pool.size=2
task.executor.max.pool.size=10
task.executor.queue=20
logging.level.org.springframework.web=OFF

server.ssl.key-store=keystore-example.p12
