#
#  Copyright (C) 2025  PChouse - Reflex√£o Estudos e Sistemas Inform·ticos, lda

# The name of the printer
name=pdf-api
# ESC/POS commands - For epson check https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=2
# use the decimal notation separated by a comma
# Initialize teh printer
init=27,64
feed=10
cut=29,86,65,4
cash_drawer=27,112,1,49,100,120