/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 * Advanced signature information attributes to be applied to a document. Restricted support for XML documents only.
 */
@Schema(description = "Advanced signature information attributes to be applied to a document. Restricted support for XML documents only.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")
@Component
@Scope(value = BeanDefinition.SCOPE_PROTOTYPE)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonFormat(with = JsonFormat.Feature.ACCEPT_CASE_INSENSITIVE_PROPERTIES)
public class AdvancedSignatureInfo {
  @SerializedName("signatureLocation")
  private String signatureLocation = null;

  @SerializedName("signatureTransform")
  private SignatureTransform signatureTransform = null;

  @SerializedName("canonicalTransform")
  private CanonicalTransform canonicalTransform = null;

  public AdvancedSignatureInfo signatureLocation(String signatureLocation) {
    this.signatureLocation = signatureLocation;
    return this;
  }

   /**
   * States the parent XML element where the signature will be contained (XAdES Enveloped).
   * @return signatureLocation
  **/
  @Schema(example = "SignatureInformation", description = "States the parent XML element where the signature will be contained (XAdES Enveloped).")
  public String getSignatureLocation() {
    return signatureLocation;
  }

  public void setSignatureLocation(String signatureLocation) {
    this.signatureLocation = signatureLocation;
  }

  public AdvancedSignatureInfo signatureTransform(SignatureTransform signatureTransform) {
    this.signatureTransform = signatureTransform;
    return this;
  }

   /**
   * Get signatureTransform
   * @return signatureTransform
  **/
  @Schema()
  public SignatureTransform getSignatureTransform() {
    return signatureTransform;
  }

  public void setSignatureTransform(SignatureTransform signatureTransform) {
    this.signatureTransform = signatureTransform;
  }

  public AdvancedSignatureInfo canonicalTransform(CanonicalTransform canonicalTransform) {
    this.canonicalTransform = canonicalTransform;
    return this;
  }

   /**
   * Get canonicalTransform
   * @return canonicalTransform
  **/
  @Schema()
  public CanonicalTransform getCanonicalTransform() {
    return canonicalTransform;
  }

  public void setCanonicalTransform(CanonicalTransform canonicalTransform) {
    this.canonicalTransform = canonicalTransform;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdvancedSignatureInfo advancedSignatureInfo = (AdvancedSignatureInfo) o;
    return Objects.equals(this.signatureLocation, advancedSignatureInfo.signatureLocation) &&
        Objects.equals(this.signatureTransform, advancedSignatureInfo.signatureTransform) &&
        Objects.equals(this.canonicalTransform, advancedSignatureInfo.canonicalTransform);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signatureLocation, signatureTransform, canonicalTransform);
  }


  @Override
  public String toString() {

      return "class AdvancedSignatureInfo {\n" +
              "    signatureLocation: " + toIndentedString(signatureLocation) + "\n" +
              "    signatureTransform: " + toIndentedString(signatureTransform) + "\n" +
              "    canonicalTransform: " + toIndentedString(canonicalTransform) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
