/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Details about the document with its content in base64 format.
 */
@Schema(description = "Details about the a document with its content in base64 format.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class Base64Document {

  @SerializedName("externalReference")
  private String externalReference = null;

  @SerializedName("name")
  private String name = null;

  /**
   * Content type of the document.
   */
  @JsonAdapter(ContentTypeEnum.Adapter.class)
  public enum ContentTypeEnum {

    APPLICATION_PDF("application/pdf"),
    TEXT_XML("text/xml"),
    APPLICATION_XML("application/xml");

    private final String value;

    ContentTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ContentTypeEnum fromValue(String input) {
      for (ContentTypeEnum b : ContentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ContentTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ContentTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public ContentTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return ContentTypeEnum.fromValue(value.toString());
      }
    }
  }

  @SerializedName("contentType")
  private ContentTypeEnum contentType = null;

  @SerializedName("base64Content")
  private String base64Content = null;

  public Base64Document externalReference(String externalReference) {
    this.externalReference = externalReference;
    return this;
  }

   /**
   * Unique external reference id set by the client service. This should be used to query the document status if an infrastructure error occurs during operation execution that could leave its status incoherent between client and server. A good approach is to have the service client id prefixed to the external reference to avoid collisions with other external references already registered in the system.
   * @return externalReference
  **/
  @Schema(example = "Ext_Ref", requiredMode = Schema.RequiredMode.REQUIRED, description = "Unique external reference id set by the client service. This should be used to query the document status if an infrastructure error occurs during operation execution that could leave its status incoherent between client and server. A good approach is to have the service client id prefixed to the external reference to avoid collisions with other external references already registered in the system.")
  public String getExternalReference() {
    return externalReference;
  }

  public void setExternalReference(String externalReference) {
    this.externalReference = externalReference;
  }

  public Base64Document name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the document.
   * @return name
  **/
  @Schema(example = "document_example.pdf", requiredMode = Schema.RequiredMode.REQUIRED, description = "Name of the document.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Base64Document contentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Content type of the document.
   * @return contentType
  **/
  @Schema(example = "application/pdf", requiredMode = Schema.RequiredMode.REQUIRED, description = "Content type of the document.")
  public ContentTypeEnum getContentType() {
    return contentType;
  }

  public void setContentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
  }

  public Base64Document base64Content(String base64Content) {
    this.base64Content = base64Content;
    return this;
  }

   /**
   * String with the document content in base64 format.
   * @return base64Content
  **/
  @Schema(example = "pdf...string...base64...=", requiredMode = Schema.RequiredMode.REQUIRED, description = "String with the document content in base64 format.")
  public String getBase64Content() {
    return base64Content;
  }

  public void setBase64Content(String base64Content) {
    this.base64Content = base64Content;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Base64Document base64Document = (Base64Document) o;
    return Objects.equals(this.externalReference, base64Document.externalReference) &&
        Objects.equals(this.name, base64Document.name) &&
        Objects.equals(this.contentType, base64Document.contentType) &&
        Objects.equals(this.base64Content, base64Document.base64Content);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalReference, name, contentType, base64Content);
  }


  @Override
  public String toString() {

      return "class Base64Document {\n" +
              "    externalReference: " + toIndentedString(externalReference) + "\n" +
              "    name: " + toIndentedString(name) + "\n" +
              "    contentType: " + toIndentedString(contentType) + "\n" +
              "    base64Content: " + toIndentedString(base64Content) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
