/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;
/**
 * Base information about an operation.
 */
@Schema(description = "Base information about an operation.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class BaseOperation {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("type")
  private OperationType type = null;

  @SerializedName("status")
  private OperationStatus status = null;

  @SerializedName("issuerCompany")
  private Company issuerCompany = null;

  @SerializedName("issuerClientServiceAlias")
  private String issuerClientServiceAlias = null;

  @SerializedName("creationDate")
  private OffsetDateTime creationDate = null;

  @SerializedName("folderExternalReference")
  private String folderExternalReference = null;

  @SerializedName("signatureQueuePriority")
  private SignatureQueuePriority signatureQueuePriority = null;

  public BaseOperation id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Operation unique id.
   * @return id
  **/
  @Schema(example = "123", requiredMode = Schema.RequiredMode.REQUIRED, description = "Operation unique id.")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public BaseOperation type(OperationType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema()
  public OperationType getType() {
    return type;
  }

  public void setType(OperationType type) {
    this.type = type;
  }

  public BaseOperation status(OperationStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema()
  public OperationStatus getStatus() {
    return status;
  }

  public void setStatus(OperationStatus status) {
    this.status = status;
  }

  public BaseOperation issuerCompany(Company issuerCompany) {
    this.issuerCompany = issuerCompany;
    return this;
  }

   /**
   * Get issuerCompany
   * @return issuerCompany
  **/
  @Schema()
  public Company getIssuerCompany() {
    return issuerCompany;
  }

  public void setIssuerCompany(Company issuerCompany) {
    this.issuerCompany = issuerCompany;
  }

  public BaseOperation issuerClientServiceAlias(String issuerClientServiceAlias) {
    this.issuerClientServiceAlias = issuerClientServiceAlias;
    return this;
  }

   /**
   * Issuer client service that created the operation.
   * @return issuerClientServiceAlias
  **/
  @Schema(description = "Issuer client service that created the operation.")
  public String getIssuerClientServiceAlias() {
    return issuerClientServiceAlias;
  }

  public void setIssuerClientServiceAlias(String issuerClientServiceAlias) {
    this.issuerClientServiceAlias = issuerClientServiceAlias;
  }

  public BaseOperation creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Operation registry date.
   * @return creationDate
  **/
  @Schema(description = "Operation registry date.")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public BaseOperation folderExternalReference(String folderExternalReference) {
    this.folderExternalReference = folderExternalReference;
    return this;
  }

   /**
   * Folder external reference.
   * @return folderExternalReference
  **/
  @Schema(description = "Folder external reference.")
  public String getFolderExternalReference() {
    return folderExternalReference;
  }

  public void setFolderExternalReference(String folderExternalReference) {
    this.folderExternalReference = folderExternalReference;
  }

  public BaseOperation signatureQueuePriority(SignatureQueuePriority signatureQueuePriority) {
    this.signatureQueuePriority = signatureQueuePriority;
    return this;
  }

   /**
   * Get signatureQueuePriority
   * @return signatureQueuePriority
  **/
  @Schema(description = "")
  public SignatureQueuePriority getSignatureQueuePriority() {
    return signatureQueuePriority;
  }

  public void setSignatureQueuePriority(SignatureQueuePriority signatureQueuePriority) {
    this.signatureQueuePriority = signatureQueuePriority;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BaseOperation baseOperation = (BaseOperation) o;
    return Objects.equals(this.id, baseOperation.id) &&
        Objects.equals(this.type, baseOperation.type) &&
        Objects.equals(this.status, baseOperation.status) &&
        Objects.equals(this.issuerCompany, baseOperation.issuerCompany) &&
        Objects.equals(this.issuerClientServiceAlias, baseOperation.issuerClientServiceAlias) &&
        Objects.equals(this.creationDate, baseOperation.creationDate) &&
        Objects.equals(this.folderExternalReference, baseOperation.folderExternalReference) &&
        Objects.equals(this.signatureQueuePriority, baseOperation.signatureQueuePriority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, status, issuerCompany, issuerClientServiceAlias, creationDate, folderExternalReference, signatureQueuePriority);
  }


  @Override
  public String toString() {

      return "class BaseOperation {\n" +
              "    id: " + toIndentedString(id) + "\n" +
              "    type: " + toIndentedString(type) + "\n" +
              "    status: " + toIndentedString(status) + "\n" +
              "    issuerCompany: " + toIndentedString(issuerCompany) + "\n" +
              "    issuerClientServiceAlias: " + toIndentedString(issuerClientServiceAlias) + "\n" +
              "    creationDate: " + toIndentedString(creationDate) + "\n" +
              "    folderExternalReference: " + toIndentedString(folderExternalReference) + "\n" +
              "    signatureQueuePriority: " + toIndentedString(signatureQueuePriority) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
