/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  * EXCLUSIVE: Exclusive Canonical XML : <a href="http://www.w3.org/2001/10/xml-exc-c14n#">...</a> * EXCLUSIVE_WITH_COMMENTS: Exclusive Canonical XML with comments : <a href="http://www.w3.org/2001/10/xml-exc-c14n#WithComments">...</a>
 */
@JsonAdapter(CanonicalTransform.Adapter.class)
public enum CanonicalTransform {
  @SerializedName("EXCLUSIVE")
  EXCLUSIVE("EXCLUSIVE"),
  @SerializedName("EXCLUSIVE_WITH_COMMENTS")
  EXCLUSIVE_WITH_COMMENTS("EXCLUSIVE_WITH_COMMENTS");

  private final String value;

  CanonicalTransform(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CanonicalTransform fromValue(String input) {
    for (CanonicalTransform b : CanonicalTransform.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CanonicalTransform> {
    @Override
    public void write(final JsonWriter jsonWriter, final CanonicalTransform enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public CanonicalTransform read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CanonicalTransform.fromValue(value);
    }
  }
}
