/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  * PENDING: Document received but not yet ciphered. Will only occur after signing. * ERROR_CIPHERING: An error occurred when ciphering. Will try again. * CIPHERED: Document content is ciphered. * NO_CIPHER: No ciphering actions will be taken.
 */
@JsonAdapter(CipherStatus.Adapter.class)
public enum CipherStatus {
  @SerializedName("PENDING")
  PENDING("PENDING"),
  @SerializedName("ERROR_CIPHERING")
  ERROR_CIPHERING("ERROR_CIPHERING"),
  @SerializedName("CIPHERED")
  CIPHERED("CIPHERED"),
  @SerializedName("NO_CIPHER")
  NO_CIPHER("NO_CIPHER");

  private final String value;

  CipherStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CipherStatus fromValue(String input) {
    for (CipherStatus b : CipherStatus.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CipherStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final CipherStatus enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public CipherStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CipherStatus.fromValue(value);
    }
  }
}
