/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  * REGISTERED: enrollment request is registered but not yet processed. * ACTIVE: company is active for usage * SUSPENDED: company suspended due to own operator management action * BLOCKED: company blocked due to admin action * DELETED: company mark for deletion
 */
@JsonAdapter(CompanyStatus.Adapter.class)
public enum CompanyStatus {
  @SerializedName("REGISTERED")
  REGISTERED("REGISTERED"),
  @SerializedName("ACTIVE")
  ACTIVE("ACTIVE"),
  @SerializedName("SUSPENDED")
  SUSPENDED("SUSPENDED"),
  @SerializedName("BLOCKED")
  BLOCKED("BLOCKED"),
  @SerializedName("DELETED")
  DELETED("DELETED");

  private final String value;

  CompanyStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CompanyStatus fromValue(String input) {
    for (CompanyStatus b : CompanyStatus.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CompanyStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final CompanyStatus enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public CompanyStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CompanyStatus.fromValue(value);
    }
  }
}
