/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;
/**
 * Company information detail.
 */
@Schema(description = "Company information detail.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class Company {
  @SerializedName("name")
  private String name = null;

  @SerializedName("vatNumber")
  private String vatNumber = null;

  @SerializedName("countryCode")
  private String countryCode = null;

  @SerializedName("i18nCode")
  private String i18nCode = null;

  @SerializedName("invoiceAddress")
  private String invoiceAddress = null;

  @SerializedName("additionalInfo")
  private String additionalInfo = null;

  @SerializedName("status")
  private CompanyStatus status = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("creationDate")
  private OffsetDateTime creationDate = null;

  @SerializedName("auditLogsActive")
  private Boolean auditLogsActive = null;

  @SerializedName("limitPeriodStartDate")
  private OffsetDateTime limitPeriodStartDate = null;

  @SerializedName("limitPeriodEndDate")
  private OffsetDateTime limitPeriodEndDate = null;

  @SerializedName("limitUsageCount")
  private Integer limitUsageCount = null;

  @SerializedName("limitCurrentConsumption")
  private Integer limitCurrentConsumption = null;

  @SerializedName("limitCurrentConsumptionLastModifiedDate")
  private OffsetDateTime limitCurrentConsumptionLastModifiedDate = null;

  @SerializedName("notifyExpiredLimit")
  private Boolean notifyExpiredLimit = null;

  public Company name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the company.
   * @return name
  **/
  @Schema(example = "ACME Corporation", requiredMode = Schema.RequiredMode.REQUIRED, description = "Name of the company.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Company vatNumber(String vatNumber) {
    this.vatNumber = vatNumber;
    return this;
  }

   /**
   * VAT Number of the company.
   * @return vatNumber
  **/
  @Schema(example = "123456789", requiredMode = Schema.RequiredMode.REQUIRED, description = "VAT Number of the company.")
  public String getVatNumber() {
    return vatNumber;
  }

  public void setVatNumber(String vatNumber) {
    this.vatNumber = vatNumber;
  }

  public Company countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
    * Country code in ISO 3166 Alpha 3 format where the VAT number of the company was issued (full country list available on <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3">...</a>).
    * @return countryCode
    **/
  @Schema(example = "PRT", requiredMode = Schema.RequiredMode.REQUIRED, description = "Country code in ISO 3166 Alpha 3 format where the VAT number of the company was issued (full country list available on https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3).")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public Company i18nCode(String i18nCode) {
    this.i18nCode = i18nCode;
    return this;
  }

   /**
   * i18n locale code of the language configured for the company.
   * @return i18nCode
  **/
  @Schema(example = "pt_PT", requiredMode = Schema.RequiredMode.REQUIRED, description = "i18n locale code of the language configured for the company.")
  public String getI18nCode() {
    return i18nCode;
  }

  public void setI18nCode(String i18nCode) {
    this.i18nCode = i18nCode;
  }

  public Company invoiceAddress(String invoiceAddress) {
    this.invoiceAddress = invoiceAddress;
    return this;
  }

   /**
   * Company address to where the invoice with the service consumptions will be issued.
   * @return invoiceAddress
  **/
  @Schema(example = "Rua do teste Nº 10, 1700 001, Lisboa - Portugal", description = "Company address to where the invoice with the service consumptions will be issued.")
  public String getInvoiceAddress() {
    return invoiceAddress;
  }

  public void setInvoiceAddress(String invoiceAddress) {
    this.invoiceAddress = invoiceAddress;
  }

  public Company additionalInfo(String additionalInfo) {
    this.additionalInfo = additionalInfo;
    return this;
  }

   /**
   * Additional information on the company.
   * @return additionalInfo
  **/
  @Schema(example = "Notas adicionais associadas à empresa", description = "Additional information on the company.")
  public String getAdditionalInfo() {
    return additionalInfo;
  }

  public void setAdditionalInfo(String additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  public Company status(CompanyStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public CompanyStatus getStatus() {
    return status;
  }

  public void setStatus(CompanyStatus status) {
    this.status = status;
  }

  public Company email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The company e-mail. Will serve for contact purposes.
   * @return email
  **/
  @Schema(example = "info@anygivendomain.com", description = "The company e-mail. Will serve for contact purposes.")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Company creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * The company registry date.
   * @return creationDate
  **/
  @Schema(description = "The company registry date.")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public Company auditLogsActive(Boolean auditLogsActive) {
    this.auditLogsActive = auditLogsActive;
    return this;
  }

   /**
   * Audit logs activation status of the company.
   * @return auditLogsActive
  **/
  @Schema(example = "true", description = "Audit logs activation status of the company.")
  public Boolean isAuditLogsActive() {
    return auditLogsActive;
  }

  public void setAuditLogsActive(Boolean auditLogsActive) {
    this.auditLogsActive = auditLogsActive;
  }

  public Company limitPeriodStartDate(OffsetDateTime limitPeriodStartDate) {
    this.limitPeriodStartDate = limitPeriodStartDate;
    return this;
  }

   /**
   * The signature limit period start date.
   * @return limitPeriodStartDate
  **/
  @Schema(description = "The signature limit period start date.")
  public OffsetDateTime getLimitPeriodStartDate() {
    return limitPeriodStartDate;
  }

  public void setLimitPeriodStartDate(OffsetDateTime limitPeriodStartDate) {
    this.limitPeriodStartDate = limitPeriodStartDate;
  }

  public Company limitPeriodEndDate(OffsetDateTime limitPeriodEndDate) {
    this.limitPeriodEndDate = limitPeriodEndDate;
    return this;
  }

   /**
   * The signature limit period end date.
   * @return limitPeriodEndDate
  **/
  @Schema(description = "The signature limit period end date.")
  public OffsetDateTime getLimitPeriodEndDate() {
    return limitPeriodEndDate;
  }

  public void setLimitPeriodEndDate(OffsetDateTime limitPeriodEndDate) {
    this.limitPeriodEndDate = limitPeriodEndDate;
  }

  public Company limitUsageCount(Integer limitUsageCount) {
    this.limitUsageCount = limitUsageCount;
    return this;
  }

   /**
   * Maximum number of signatures configured.
   * @return limitUsageCount
  **/
  @Schema(example = "5000000", description = "Maximum number of signatures configured.")
  public Integer getLimitUsageCount() {
    return limitUsageCount;
  }

  public void setLimitUsageCount(Integer limitUsageCount) {
    this.limitUsageCount = limitUsageCount;
  }

  public Company limitCurrentConsumption(Integer limitCurrentConsumption) {
    this.limitCurrentConsumption = limitCurrentConsumption;
    return this;
  }

   /**
   * Actual number of signatures consumed.
   * @return limitCurrentConsumption
  **/
  @Schema(example = "5000", description = "Actual number of signatures consumed.")
  public Integer getLimitCurrentConsumption() {
    return limitCurrentConsumption;
  }

  public void setLimitCurrentConsumption(Integer limitCurrentConsumption) {
    this.limitCurrentConsumption = limitCurrentConsumption;
  }

  public Company limitCurrentConsumptionLastModifiedDate(OffsetDateTime limitCurrentConsumptionLastModifiedDate) {
    this.limitCurrentConsumptionLastModifiedDate = limitCurrentConsumptionLastModifiedDate;
    return this;
  }

   /**
   * The date of the current consumption last update.
   * @return limitCurrentConsumptionLastModifiedDate
  **/
  @Schema(description = "The date of the current consumption last update.")
  public OffsetDateTime getLimitCurrentConsumptionLastModifiedDate() {
    return limitCurrentConsumptionLastModifiedDate;
  }

  public void setLimitCurrentConsumptionLastModifiedDate(OffsetDateTime limitCurrentConsumptionLastModifiedDate) {
    this.limitCurrentConsumptionLastModifiedDate = limitCurrentConsumptionLastModifiedDate;
  }

  public Company notifyExpiredLimit(Boolean notifyExpiredLimit) {
    this.notifyExpiredLimit = notifyExpiredLimit;
    return this;
  }

   /**
   * Get notifyExpiredLimit
   * @return notifyExpiredLimit
  **/
  @Schema(description = "")
  public Boolean isNotifyExpiredLimit() {
    return notifyExpiredLimit;
  }

  public void setNotifyExpiredLimit(Boolean notifyExpiredLimit) {
    this.notifyExpiredLimit = notifyExpiredLimit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Company company = (Company) o;
    return Objects.equals(this.name, company.name) &&
        Objects.equals(this.vatNumber, company.vatNumber) &&
        Objects.equals(this.countryCode, company.countryCode) &&
        Objects.equals(this.i18nCode, company.i18nCode) &&
        Objects.equals(this.invoiceAddress, company.invoiceAddress) &&
        Objects.equals(this.additionalInfo, company.additionalInfo) &&
        Objects.equals(this.status, company.status) &&
        Objects.equals(this.email, company.email) &&
        Objects.equals(this.creationDate, company.creationDate) &&
        Objects.equals(this.auditLogsActive, company.auditLogsActive) &&
        Objects.equals(this.limitPeriodStartDate, company.limitPeriodStartDate) &&
        Objects.equals(this.limitPeriodEndDate, company.limitPeriodEndDate) &&
        Objects.equals(this.limitUsageCount, company.limitUsageCount) &&
        Objects.equals(this.limitCurrentConsumption, company.limitCurrentConsumption) &&
        Objects.equals(this.limitCurrentConsumptionLastModifiedDate, company.limitCurrentConsumptionLastModifiedDate) &&
        Objects.equals(this.notifyExpiredLimit, company.notifyExpiredLimit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, vatNumber, countryCode, i18nCode, invoiceAddress, additionalInfo, status, email, creationDate, auditLogsActive, limitPeriodStartDate, limitPeriodEndDate, limitUsageCount, limitCurrentConsumption, limitCurrentConsumptionLastModifiedDate, notifyExpiredLimit);
  }


  @Override
  public String toString() {

      return "class Company {\n" +
              "    name: " + toIndentedString(name) + "\n" +
              "    vatNumber: " + toIndentedString(vatNumber) + "\n" +
              "    countryCode: " + toIndentedString(countryCode) + "\n" +
              "    i18nCode: " + toIndentedString(i18nCode) + "\n" +
              "    invoiceAddress: " + toIndentedString(invoiceAddress) + "\n" +
              "    additionalInfo: " + toIndentedString(additionalInfo) + "\n" +
              "    status: " + toIndentedString(status) + "\n" +
              "    email: " + toIndentedString(email) + "\n" +
              "    creationDate: " + toIndentedString(creationDate) + "\n" +
              "    auditLogsActive: " + toIndentedString(auditLogsActive) + "\n" +
              "    limitPeriodStartDate: " + toIndentedString(limitPeriodStartDate) + "\n" +
              "    limitPeriodEndDate: " + toIndentedString(limitPeriodEndDate) + "\n" +
              "    limitUsageCount: " + toIndentedString(limitUsageCount) + "\n" +
              "    limitCurrentConsumption: " + toIndentedString(limitCurrentConsumption) + "\n" +
              "    limitCurrentConsumptionLastModifiedDate: " + toIndentedString(limitCurrentConsumptionLastModifiedDate) + "\n" +
              "    notifyExpiredLimit: " + toIndentedString(notifyExpiredLimit) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
