/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  * PENDING: Delivery is registered bas has not been executed. * SENT: Notification was sent to person, but a reception has not yet been confirmed. * RECEIVED: Person has confirmed document reception. * SENDING_ERROR: Error occurred when sending the notification. Will try again. * SENDING_FAILED: Sending error retries has reached its limit. Notification was not sent and system will not retry.
 */
@JsonAdapter(DeliveryStatus.Adapter.class)
public enum DeliveryStatus {
  @SerializedName("PENDING")
  PENDING("PENDING"),
  @SerializedName("SENT")
  SENT("SENT"),
  @SerializedName("RECEIVED")
  RECEIVED("RECEIVED"),
  @SerializedName("SENDING_ERROR")
  SENDING_ERROR("SENDING_ERROR"),
  @SerializedName("SENDING_FAILED")
  SENDING_FAILED("SENDING_FAILED");

  private final String value;

  DeliveryStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DeliveryStatus fromValue(String input) {
    for (DeliveryStatus b : DeliveryStatus.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<DeliveryStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final DeliveryStatus enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public DeliveryStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DeliveryStatus.fromValue(value);
    }
  }
}
