/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * Delivery information for sending the given document or folder to a third party.
 */
@Schema(description = "Delivery information for sending the given document or folder to a third-party.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class DeliveryInfo {
  @SerializedName("attachDocuments")
  private Boolean attachDocuments = false;

  @SerializedName("personReceiver")
  private List<Person> personReceiver = new ArrayList<>();

  public DeliveryInfo attachDocuments(Boolean attachDocuments) {
    this.attachDocuments = attachDocuments;
    return this;
  }

   /**
   * Allows informing if signed documents should be attached to the notification email.
   * @return attachDocuments
  **/
  @Schema(example = "false", description = "Allows informing if signed documents should be attached to the notification email.")
  public Boolean isAttachDocuments() {
    return attachDocuments;
  }

  public void setAttachDocuments(Boolean attachDocuments) {
    this.attachDocuments = attachDocuments;
  }

  public DeliveryInfo personReceiver(List<Person> personReceiver) {
    this.personReceiver = personReceiver;
    return this;
  }

  public DeliveryInfo addPersonReceiverItem(Person personReceiverItem) {
    this.personReceiver.add(personReceiverItem);
    return this;
  }

   /**
   * Persons that will receive the document.
   * @return personReceiver
  **/
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Persons that will receive the document.")
  public List<Person> getPersonReceiver() {
    return personReceiver;
  }

  public void setPersonReceiver(List<Person> personReceiver) {
    this.personReceiver = personReceiver;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeliveryInfo deliveryInfo = (DeliveryInfo) o;
    return Objects.equals(this.attachDocuments, deliveryInfo.attachDocuments) &&
        Objects.equals(this.personReceiver, deliveryInfo.personReceiver);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachDocuments, personReceiver);
  }


  @Override
  public String toString() {

      return "class DeliveryInfo {\n" +
              "    attachDocuments: " + toIndentedString(attachDocuments) + "\n" +
              "    personReceiver: " + toIndentedString(personReceiver) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
