/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Base information about a document.
 */
@Schema(description = "Base information about a document.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class Document {
  @SerializedName("externalReference")
  private String externalReference = null;

  @SerializedName("name")
  private String name = null;

  /**
   * Content type of the document.
   */
  @JsonAdapter(ContentTypeEnum.Adapter.class)
  public enum ContentTypeEnum {
    @SerializedName("application/pdf, text/xml, application/xml")
    APPLICATION_PDF_TEXT_XML_APPLICATION_XML("application/pdf, text/xml, application/xml");

    private final String value;

    ContentTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ContentTypeEnum fromValue(String input) {
      for (ContentTypeEnum b : ContentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ContentTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ContentTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public ContentTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ContentTypeEnum.fromValue(value);
      }
    }
  }  @SerializedName("contentType")
  private ContentTypeEnum contentType = null;

  public Document externalReference(String externalReference) {
    this.externalReference = externalReference;
    return this;
  }

   /**
   * Unique external reference id set by the client service. This should be used to query the document status if an infrastructure error occurs during operation execution that could leave its status incoherent between client and server. A good approach is to have the service client id prefixed to the external reference to avoid collisions with other external references already registered in the system.
   * @return externalReference
  **/
  @Schema(example = "Ext_Ref", requiredMode = Schema.RequiredMode.REQUIRED, description = "Unique external reference id set by the client service. This should be used to query the document status if an infrastructure error occurs during operation execution that could leave its status incoherent between client and server. A good approach is to have the service client id prefixed to the external reference to avoid collisions with other external references already registered in the system.")
  public String getExternalReference() {
    return externalReference;
  }

  public void setExternalReference(String externalReference) {
    this.externalReference = externalReference;
  }

  public Document name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the document.
   * @return name
  **/
  @Schema(example = "document_example.pdf", requiredMode = Schema.RequiredMode.REQUIRED, description = "Name of the document.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Document contentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Content type of the document.
   * @return contentType
  **/
  @Schema(example = "application/pdf", requiredMode = Schema.RequiredMode.REQUIRED, description = "Content type of the document.")
  public ContentTypeEnum getContentType() {
    return contentType;
  }

  public void setContentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Document document = (Document) o;
    return Objects.equals(this.externalReference, document.externalReference) &&
        Objects.equals(this.name, document.name) &&
        Objects.equals(this.contentType, document.contentType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalReference, name, contentType);
  }


  @Override
  public String toString() {

      return "class Document {\n" +
              "    externalReference: " + toIndentedString(externalReference) + "\n" +
              "    name: " + toIndentedString(name) + "\n" +
              "    contentType: " + toIndentedString(contentType) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
