/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
/**
 * DocumentSignBody1
 */

@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class DocumentSignBody1 {
  @SerializedName("files")
  private List<File> files = new ArrayList<>();

  @SerializedName("signRequest")
  private SignRequestDocument signRequest = null;

  public DocumentSignBody1 files(List<File> files) {
    this.files = files;
    return this;
  }

  public DocumentSignBody1 addFilesItem(File filesItem) {
    this.files.add(filesItem);
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
  public List<File> getFiles() {
    return files;
  }

  public void setFiles(List<File> files) {
    this.files = files;
  }

  public DocumentSignBody1 signRequest(SignRequestDocument signRequest) {
    this.signRequest = signRequest;
    return this;
  }

   /**
   * Get signRequest
   * @return signRequest
  **/
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
  public SignRequestDocument getSignRequest() {
    return signRequest;
  }

  public void setSignRequest(SignRequestDocument signRequest) {
    this.signRequest = signRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentSignBody1 documentSignBody1 = (DocumentSignBody1) o;
    return Objects.equals(this.files, documentSignBody1.files) &&
        Objects.equals(this.signRequest, documentSignBody1.signRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(files, signRequest);
  }


  @Override
  public String toString() {

      return "class DocumentSignBody1 {\n" +
              "    files: " + toIndentedString(files) + "\n" +
              "    signRequest: " + toIndentedString(signRequest) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
