/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Information about the document attributes.
 */
@Schema(description = "Information about the document attributes.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class DocumentAttributeResponse {
  @SerializedName("attributeKey")
  private DocumentAttributeKey attributeKey = null;

  @SerializedName("attributeValue")
  private String attributeValue = null;

  public DocumentAttributeResponse attributeKey(DocumentAttributeKey attributeKey) {
    this.attributeKey = attributeKey;
    return this;
  }

   /**
   * Get attributeKey
   * @return attributeKey
  **/
  @Schema()
  public DocumentAttributeKey getAttributeKey() {
    return attributeKey;
  }

  public void setAttributeKey(DocumentAttributeKey attributeKey) {
    this.attributeKey = attributeKey;
  }

  public DocumentAttributeResponse attributeValue(String attributeValue) {
    this.attributeValue = attributeValue;
    return this;
  }

   /**
   * Value of document attribute.
   * @return attributeValue
  **/
  @Schema(example = "Test API reason", description = "Value of document attribute.")
  public String getAttributeValue() {
    return attributeValue;
  }

  public void setAttributeValue(String attributeValue) {
    this.attributeValue = attributeValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentAttributeResponse documentAttributeResponse = (DocumentAttributeResponse) o;
    return Objects.equals(this.attributeKey, documentAttributeResponse.attributeKey) &&
        Objects.equals(this.attributeValue, documentAttributeResponse.attributeValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeKey, attributeValue);
  }


  @Override
  public String toString() {

      return "class DocumentAttributeResponse {\n" +
              "    attributeKey: " + toIndentedString(attributeKey) + "\n" +
              "    attributeValue: " + toIndentedString(attributeValue) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
