/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * Details about the document response.
 */
@Schema(description = "Details about the document response.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class DocumentResponse {
  @SerializedName("externalReference")
  private String externalReference = null;

  @SerializedName("name")
  private String name = null;

  /**
   * Content type of the document.
   */
  @JsonAdapter(ContentTypeEnum.Adapter.class)
  public enum ContentTypeEnum {
    @SerializedName("application/pdf, text/xml, application/xml")
    APPLICATION_PDF_TEXT_XML_APPLICATION_XML("application/pdf, text/xml, application/xml");

    private final String value;

    ContentTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ContentTypeEnum fromValue(String input) {
      for (ContentTypeEnum b : ContentTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ContentTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ContentTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public ContentTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ContentTypeEnum.fromValue(value);
      }
    }
  }  @SerializedName("contentType")
  private ContentTypeEnum contentType = null;

  @SerializedName("internalId")
  private Long internalId = null;

  @SerializedName("signStatus")
  private SigningStatus signStatus = null;

  @SerializedName("signError")
  private SigningError signError = null;

  @SerializedName("cipherStatus")
  private CipherStatus cipherStatus = null;

  @SerializedName("storageStatus")
  private StorageStatus storageStatus = null;

  @SerializedName("contentLength")
  private Long contentLength = null;

  @SerializedName("additionalContentLength")
  private Long additionalContentLength = null;

  @SerializedName("receptionDate")
  private OffsetDateTime receptionDate = null;

  @SerializedName("storagePeriod")
  private Long storagePeriod = null;

  @SerializedName("storageEndDate")
  private OffsetDateTime storageEndDate = null;

  @SerializedName("signedContent")
  private String signedContent = null;

  @SerializedName("documentAttributes")
  private List<DocumentAttributeResponse> documentAttributes = null;

  public DocumentResponse externalReference(String externalReference) {
    this.externalReference = externalReference;
    return this;
  }

   /**
   * Unique external reference id set by the client service. This should be used to query the document status if an infrastructure error occurs during operation execution that could leave its status incoherent between client and server. A good approach is to have the service client id prefixed to the external reference to avoid collisions with other external references already registered in the system.
   * @return externalReference
  **/
  @Schema(example = "Ext_Ref", requiredMode = Schema.RequiredMode.REQUIRED, description = "Unique external reference id set by the client service. This should be used to query the document status if an infrastructure error occurs during operation execution that could leave its status incoherent between client and server. A good approach is to have the service client id prefixed to the external reference to avoid collisions with other external references already registered in the system.")
  public String getExternalReference() {
    return externalReference;
  }

  public void setExternalReference(String externalReference) {
    this.externalReference = externalReference;
  }

  public DocumentResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the document.
   * @return name
  **/
  @Schema(example = "document_example.pdf", required = true, description = "Name of the document.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DocumentResponse contentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Content type of the document.
   * @return contentType
  **/
  @Schema(example = "application/pdf", required = true, description = "Content type of the document.")
  public ContentTypeEnum getContentType() {
    return contentType;
  }

  public void setContentType(ContentTypeEnum contentType) {
    this.contentType = contentType;
  }

  public DocumentResponse internalId(Long internalId) {
    this.internalId = internalId;
    return this;
  }

   /**
   * Internal Id of the document in the eInvoice system.
   * @return internalId
  **/
  @Schema(example = "123", description = "Internal Id of the document in the eInvoice system.")
  public Long getInternalId() {
    return internalId;
  }

  public void setInternalId(Long internalId) {
    this.internalId = internalId;
  }

  public DocumentResponse signStatus(SigningStatus signStatus) {
    this.signStatus = signStatus;
    return this;
  }

   /**
   * Get signStatus
   * @return signStatus
  **/
  @Schema(description = "")
  public SigningStatus getSignStatus() {
    return signStatus;
  }

  public void setSignStatus(SigningStatus signStatus) {
    this.signStatus = signStatus;
  }

  public DocumentResponse signError(SigningError signError) {
    this.signError = signError;
    return this;
  }

   /**
   * Get signError
   * @return signError
  **/
  @Schema(description = "")
  public SigningError getSignError() {
    return signError;
  }

  public void setSignError(SigningError signError) {
    this.signError = signError;
  }

  public DocumentResponse cipherStatus(CipherStatus cipherStatus) {
    this.cipherStatus = cipherStatus;
    return this;
  }

   /**
   * Get cipherStatus
   * @return cipherStatus
  **/
  @Schema(description = "")
  public CipherStatus getCipherStatus() {
    return cipherStatus;
  }

  public void setCipherStatus(CipherStatus cipherStatus) {
    this.cipherStatus = cipherStatus;
  }

  public DocumentResponse storageStatus(StorageStatus storageStatus) {
    this.storageStatus = storageStatus;
    return this;
  }

   /**
   * Get storageStatus
   * @return storageStatus
  **/
  @Schema(description = "")
  public StorageStatus getStorageStatus() {
    return storageStatus;
  }

  public void setStorageStatus(StorageStatus storageStatus) {
    this.storageStatus = storageStatus;
  }

  public DocumentResponse contentLength(Long contentLength) {
    this.contentLength = contentLength;
    return this;
  }

   /**
   * Content length in bytes of the original/pre-signature content.
   * @return contentLength
  **/
  @Schema(example = "10", description = "Content length in bytes of the original/pre-signature content.")
  public Long getContentLength() {
    return contentLength;
  }

  public void setContentLength(Long contentLength) {
    this.contentLength = contentLength;
  }

  public DocumentResponse additionalContentLength(Long additionalContentLength) {
    this.additionalContentLength = additionalContentLength;
    return this;
  }

   /**
   * Additional original/pre-signature content length in bytes that exceeded the subscribed service limit.
   * @return additionalContentLength
  **/
  @Schema(example = "11", description = "Additional original/pre-signature content length in bytes that exceeded the subscribed service limit.")
  public Long getAdditionalContentLength() {
    return additionalContentLength;
  }

  public void setAdditionalContentLength(Long additionalContentLength) {
    this.additionalContentLength = additionalContentLength;
  }

  public DocumentResponse receptionDate(OffsetDateTime receptionDate) {
    this.receptionDate = receptionDate;
    return this;
  }

   /**
   * Instant when the document was received in the system.
   * @return receptionDate
  **/
  @Schema(description = "Instant when the document was received in the system.")
  public OffsetDateTime getReceptionDate() {
    return receptionDate;
  }

  public void setReceptionDate(OffsetDateTime receptionDate) {
    this.receptionDate = receptionDate;
  }

  public DocumentResponse storagePeriod(Long storagePeriod) {
    this.storagePeriod = storagePeriod;
    return this;
  }

   /**
   * Period length (in months) to when the document will be stored. Storage date limit is computed with receptionData + storagePeriod.
   * @return storagePeriod
  **/
  @Schema(example = "120", description = "Period length (in months) to when the document will be stored. Storage date limit is computed with receptionData + storagePeriod.")
  public Long getStoragePeriod() {
    return storagePeriod;
  }

  public void setStoragePeriod(Long storagePeriod) {
    this.storagePeriod = storagePeriod;
  }

  public DocumentResponse storageEndDate(OffsetDateTime storageEndDate) {
    this.storageEndDate = storageEndDate;
    return this;
  }

   /**
   * Instant until when the the document will be stored in the system.
   * @return storageEndDate
  **/
  @Schema(description = "Instant until when the the document will be stored in the system.")
  public OffsetDateTime getStorageEndDate() {
    return storageEndDate;
  }

  public void setStorageEndDate(OffsetDateTime storageEndDate) {
    this.storageEndDate = storageEndDate;
  }

  public DocumentResponse signedContent(String signedContent) {
    this.signedContent = signedContent;
    return this;
  }

   /**
   * Signed content, encoded in base 64 format, of the original document
   * @return signedContent
  **/
  @Schema(example = "aGVsbG8gd29ybGQK", description = "Signed content, encoded in base 64 format, of the original document")
  public String getSignedContent() {
    return signedContent;
  }

  public void setSignedContent(String signedContent) {
    this.signedContent = signedContent;
  }

  public DocumentResponse documentAttributes(List<DocumentAttributeResponse> documentAttributes) {
    this.documentAttributes = documentAttributes;
    return this;
  }

  public DocumentResponse addDocumentAttributesItem(DocumentAttributeResponse documentAttributesItem) {
    if (this.documentAttributes == null) {
      this.documentAttributes = new ArrayList<DocumentAttributeResponse>();
    }
    this.documentAttributes.add(documentAttributesItem);
    return this;
  }

   /**
   * Get documentAttributes
   * @return documentAttributes
  **/
  @Schema(description = "")
  public List<DocumentAttributeResponse> getDocumentAttributes() {
    return documentAttributes;
  }

  public void setDocumentAttributes(List<DocumentAttributeResponse> documentAttributes) {
    this.documentAttributes = documentAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentResponse documentResponse = (DocumentResponse) o;
    return Objects.equals(this.externalReference, documentResponse.externalReference) &&
        Objects.equals(this.name, documentResponse.name) &&
        Objects.equals(this.contentType, documentResponse.contentType) &&
        Objects.equals(this.internalId, documentResponse.internalId) &&
        Objects.equals(this.signStatus, documentResponse.signStatus) &&
        Objects.equals(this.signError, documentResponse.signError) &&
        Objects.equals(this.cipherStatus, documentResponse.cipherStatus) &&
        Objects.equals(this.storageStatus, documentResponse.storageStatus) &&
        Objects.equals(this.contentLength, documentResponse.contentLength) &&
        Objects.equals(this.additionalContentLength, documentResponse.additionalContentLength) &&
        Objects.equals(this.receptionDate, documentResponse.receptionDate) &&
        Objects.equals(this.storagePeriod, documentResponse.storagePeriod) &&
        Objects.equals(this.storageEndDate, documentResponse.storageEndDate) &&
        Objects.equals(this.signedContent, documentResponse.signedContent) &&
        Objects.equals(this.documentAttributes, documentResponse.documentAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalReference, name, contentType, internalId, signStatus, signError, cipherStatus, storageStatus, contentLength, additionalContentLength, receptionDate, storagePeriod, storageEndDate, signedContent, documentAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentResponse {\n");
    
    sb.append("    externalReference: ").append(toIndentedString(externalReference)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    internalId: ").append(toIndentedString(internalId)).append("\n");
    sb.append("    signStatus: ").append(toIndentedString(signStatus)).append("\n");
    sb.append("    signError: ").append(toIndentedString(signError)).append("\n");
    sb.append("    cipherStatus: ").append(toIndentedString(cipherStatus)).append("\n");
    sb.append("    storageStatus: ").append(toIndentedString(storageStatus)).append("\n");
    sb.append("    contentLength: ").append(toIndentedString(contentLength)).append("\n");
    sb.append("    additionalContentLength: ").append(toIndentedString(additionalContentLength)).append("\n");
    sb.append("    receptionDate: ").append(toIndentedString(receptionDate)).append("\n");
    sb.append("    storagePeriod: ").append(toIndentedString(storagePeriod)).append("\n");
    sb.append("    storageEndDate: ").append(toIndentedString(storageEndDate)).append("\n");
    sb.append("    signedContent: ").append(toIndentedString(signedContent)).append("\n");
    sb.append("    documentAttributes: ").append(toIndentedString(documentAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
