/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Error response information.
 */
@Schema(description = "Error response information.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class ErrorResponse {
  @SerializedName("errorCode")
  private String errorCode = null;

  @SerializedName("errorCodeDescription")
  private String errorCodeDescription = null;

  @SerializedName("causeMessage")
  private String causeMessage = null;

  public ErrorResponse errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Internal error code for which an error handler can map to.
   * @return errorCode
  **/
  @Schema(example = "0.0.2", description = "Internal error code for which a error handler can map to.")
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }

  public ErrorResponse errorCodeDescription(String errorCodeDescription) {
    this.errorCodeDescription = errorCodeDescription;
    return this;
  }

   /**
   * Internal error code description stating a hint for a possible cause.
   * @return errorCodeDescription
  **/
  @Schema(example = "Mandatory attribute is missing.", description = "Internal error code description stating a hint for a possible cause.")
  public String getErrorCodeDescription() {
    return errorCodeDescription;
  }

  public void setErrorCodeDescription(String errorCodeDescription) {
    this.errorCodeDescription = errorCodeDescription;
  }

  public ErrorResponse causeMessage(String causeMessage) {
    this.causeMessage = causeMessage;
    return this;
  }

   /**
   * Server dynamic message with further error cause details 
   * @return causeMessage
  **/
  @Schema(example = "missing signDocumentRequest.document", description = "Server dynamic message with further error cause details ")
  public String getCauseMessage() {
    return causeMessage;
  }

  public void setCauseMessage(String causeMessage) {
    this.causeMessage = causeMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorResponse errorResponse = (ErrorResponse) o;
    return Objects.equals(this.errorCode, errorResponse.errorCode) &&
        Objects.equals(this.errorCodeDescription, errorResponse.errorCodeDescription) &&
        Objects.equals(this.causeMessage, errorResponse.causeMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorCode, errorCodeDescription, causeMessage);
  }


  @Override
  public String toString() {

      return "class ErrorResponse {\n" +
              "    errorCode: " + toIndentedString(errorCode) + "\n" +
              "    errorCodeDescription: " + toIndentedString(errorCodeDescription) + "\n" +
              "    causeMessage: " + toIndentedString(causeMessage) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
