/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  * DOCUMENT: The folder represents a list of documents. * HASH: The folder represents a list of hashes.
 */
@JsonAdapter(FolderContent.Adapter.class)
public enum FolderContent {
  @SerializedName("DOCUMENT")
  DOCUMENT("DOCUMENT"),
  @SerializedName("HASH")
  HASH("HASH");

  private final String value;

  FolderContent(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static FolderContent fromValue(String input) {
    for (FolderContent b : FolderContent.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<FolderContent> {
    @Override
    public void write(final JsonWriter jsonWriter, final FolderContent enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public FolderContent read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return FolderContent.fromValue(value);
    }
  }
}
