/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Information about a document folder.
 */
@Schema(description = "Information about a document folder.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class Folder {
  @SerializedName("folderId")
  private String folderId = null;

  @SerializedName("externalReference")
  private String externalReference = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("folderContent")
  private FolderContent folderContent = null;

  public Folder folderId(String folderId) {
    this.folderId = folderId;
    return this;
  }

   /**
   * Folder unique id that holds all the documents handled on a given request.
   * @return folderId
  **/
  @Schema(description = "Folder unique id that holds all the documents handled on a given request.")
  public String getFolderId() {
    return folderId;
  }

  public void setFolderId(String folderId) {
    this.folderId = folderId;
  }

  public Folder externalReference(String externalReference) {
    this.externalReference = externalReference;
    return this;
  }

   /**
   * Folder external reference as submitted by the client service.
   * @return externalReference
  **/
  @Schema(description = "Folder external reference as submitted by the client service.")
  public String getExternalReference() {
    return externalReference;
  }

  public void setExternalReference(String externalReference) {
    this.externalReference = externalReference;
  }

  public Folder description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Folder description information.
   * @return description
  **/
  @Schema(description = "Folder description information.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Folder folderContent(FolderContent folderContent) {
    this.folderContent = folderContent;
    return this;
  }

   /**
   * Get folderContent
   * @return folderContent
  **/
  @Schema()
  public FolderContent getFolderContent() {
    return folderContent;
  }

  public void setFolderContent(FolderContent folderContent) {
    this.folderContent = folderContent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Folder folder = (Folder) o;
    return Objects.equals(this.folderId, folder.folderId) &&
        Objects.equals(this.externalReference, folder.externalReference) &&
        Objects.equals(this.description, folder.description) &&
        Objects.equals(this.folderContent, folder.folderContent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(folderId, externalReference, description, folderContent);
  }


  @Override
  public String toString() {

      return "class Folder {\n" +
              "    folderId: " + toIndentedString(folderId) + "\n" +
              "    externalReference: " + toIndentedString(externalReference) + "\n" +
              "    description: " + toIndentedString(description) + "\n" +
              "    folderContent: " + toIndentedString(folderContent) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
