/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  * PENDING_EXECUTION: Operation registered and awaiting execution. * EXECUTED: Operation executed successfully. * EXECUTION_ERROR: Error occurred when trying to execute operation. Will try again. * EXECUTION_FAILED: Exceeded all retries for execution errors, system has given up and will not try again.
 */
@JsonAdapter(OperationStatus.Adapter.class)
public enum OperationStatus {
  @SerializedName("PENDING_EXECUTION")
  PENDING_EXECUTION("PENDING_EXECUTION"),
  @SerializedName("EXECUTED")
  EXECUTED("EXECUTED"),
  @SerializedName("EXECUTION_ERROR")
  EXECUTION_ERROR("EXECUTION_ERROR"),
  @SerializedName("EXECUTION_FAILED")
  EXECUTION_FAILED("EXECUTION_FAILED");

  private final String value;

  OperationStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OperationStatus fromValue(String input) {
    for (OperationStatus b : OperationStatus.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<OperationStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final OperationStatus enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public OperationStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OperationStatus.fromValue(value);
    }
  }
}
