/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import pt.pchouse.pdf.api.sign.multicert.model.DeliveryStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * A person information.
 */
@Schema(description = "A person information.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class Person {
  @SerializedName("email")
  private String email = null;

  @SerializedName("deliveryStatus")
  private DeliveryStatus deliveryStatus = null;

  public Person email(String email) {
    this.email = email;
    return this;
  }

   /**
   * E-Mail contact address.
   * @return email
  **/
  @Schema(example = "john.doe@anygivendomain.com", requiredMode = Schema.RequiredMode.REQUIRED, description = "E-Mail contact address.")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Person deliveryStatus(DeliveryStatus deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
    return this;
  }

   /**
   * Get deliveryStatus
   * @return deliveryStatus
  **/
  @Schema()
  public DeliveryStatus getDeliveryStatus() {
    return deliveryStatus;
  }

  public void setDeliveryStatus(DeliveryStatus deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Person person = (Person) o;
    return Objects.equals(this.email, person.email) &&
        Objects.equals(this.deliveryStatus, person.deliveryStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, deliveryStatus);
  }


  @Override
  public String toString() {

      return "class Person {\n" +
              "    email: " + toIndentedString(email) + "\n" +
              "    deliveryStatus: " + toIndentedString(deliveryStatus) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
