/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Preservation information for the content of the document or folder.
 */
@Schema(description = "Preservation information for the content of the document or folder.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class PreservationInfo {
  @SerializedName("preserveContent")
  private Boolean preserveContent = false;

  @SerializedName("alias")
  private String alias = null;

  @SerializedName("deliveryInfo")
  private DeliveryInfo deliveryInfo = null;

  public PreservationInfo preserveContent(Boolean preserveContent) {
    this.preserveContent = preserveContent;
    return this;
  }

   /**
   * States if document integrity is to be stored and preserved for the custody duration period. If false, document will only be stored for further consultation.
   * @return preserveContent
  **/
  @Schema(example = "false", requiredMode = Schema.RequiredMode.REQUIRED, description = "States if document integrity is to be stored and preserved for the custody duration period. If false, document will only be stored for further consultation.")
  public Boolean isPreserveContent() {
    return preserveContent;
  }

  public void setPreserveContent(Boolean preserveContent) {
    this.preserveContent = preserveContent;
  }

  public PreservationInfo alias(String alias) {
    this.alias = alias;
    return this;
  }

   /**
   * Document alias that is to be presented to the end user. Note: this property is not being used.
   * @return alias
  **/
  @Schema(example = "document_pretty_name.pdf", description = "Document alias that is to be presented to the end user. Note: this property is not being used.")
  public String getAlias() {
    return alias;
  }

  public void setAlias(String alias) {
    this.alias = alias;
  }

  public PreservationInfo deliveryInfo(DeliveryInfo deliveryInfo) {
    this.deliveryInfo = deliveryInfo;
    return this;
  }

   /**
   * Get deliveryInfo
   * @return deliveryInfo
  **/
  @Schema()
  public DeliveryInfo getDeliveryInfo() {
    return deliveryInfo;
  }

  public void setDeliveryInfo(DeliveryInfo deliveryInfo) {
    this.deliveryInfo = deliveryInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PreservationInfo preservationInfo = (PreservationInfo) o;
    return Objects.equals(this.preserveContent, preservationInfo.preserveContent) &&
        Objects.equals(this.alias, preservationInfo.alias) &&
        Objects.equals(this.deliveryInfo, preservationInfo.deliveryInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preserveContent, alias, deliveryInfo);
  }


  @Override
  public String toString() {

      return "class PreservationInfo {\n" +
              "    preserveContent: " + toIndentedString(preserveContent) + "\n" +
              "    alias: " + toIndentedString(alias) + "\n" +
              "    deliveryInfo: " + toIndentedString(deliveryInfo) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
