/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;
/**
 * Details on controlling priorities in signature queues.
 */
@Schema(description = "Details on controlling priorities in signature queues.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class SignatureQueuePriority {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("startTime")
  private OffsetDateTime startTime = null;

  @SerializedName("endTime")
  private OffsetDateTime endTime = null;

  @SerializedName("defaultPriority")
  private Boolean defaultPriority = false;

   /**
   * Id for queue priority reference.
   * @return id
  **/
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Id for queue priority reference.")
  public Long getId() {
    return id;
  }

  public SignatureQueuePriority name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name for queue priority reference.
   * @return name
  **/
  @Schema(example = "DEFAULT", requiredMode = Schema.RequiredMode.REQUIRED, description = "Name for queue priority reference.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SignatureQueuePriority startTime(OffsetDateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Time limit to start the queue.
   * @return startTime
  **/
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Time limit to start the queue.")
  public OffsetDateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }

  public SignatureQueuePriority endTime(OffsetDateTime endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Time limit to end the queue.
   * @return endTime
  **/
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Time limit to end the queue.")
  public OffsetDateTime getEndTime() {
    return endTime;
  }

  public void setEndTime(OffsetDateTime endTime) {
    this.endTime = endTime;
  }

  public SignatureQueuePriority defaultPriority(Boolean defaultPriority) {
    this.defaultPriority = defaultPriority;
    return this;
  }

   /**
   * Define the default signature queue priority.
   * @return defaultPriority
  **/
  @Schema(example = "false", description = "Define the default signature queue priority.")
  public Boolean isDefaultPriority() {
    return defaultPriority;
  }

  public void setDefaultPriority(Boolean defaultPriority) {
    this.defaultPriority = defaultPriority;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureQueuePriority signatureQueuePriority = (SignatureQueuePriority) o;
    return Objects.equals(this.id, signatureQueuePriority.id) &&
        Objects.equals(this.name, signatureQueuePriority.name) &&
        Objects.equals(this.startTime, signatureQueuePriority.startTime) &&
        Objects.equals(this.endTime, signatureQueuePriority.endTime) &&
        Objects.equals(this.defaultPriority, signatureQueuePriority.defaultPriority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, startTime, endTime, defaultPriority);
  }


  @Override
  public String toString() {

      return "class SignatureQueuePriority {\n" +
              "    id: " + toIndentedString(id) + "\n" +
              "    name: " + toIndentedString(name) + "\n" +
              "    startTime: " + toIndentedString(startTime) + "\n" +
              "    endTime: " + toIndentedString(endTime) + "\n" +
              "    defaultPriority: " + toIndentedString(defaultPriority) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
