/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  * RECEIVED: Document has been received but no further action was taken. * ERROR_SIGNING: An error has occured when signing was attempted. * SIGNED: A digital signature was successfully applied to the document.
 */
@JsonAdapter(SigningStatus.Adapter.class)
public enum SigningStatus {
  @SerializedName("RECEIVED")
  RECEIVED("RECEIVED"),
  @SerializedName("ERROR_SIGNING")
  ERROR_SIGNING("ERROR_SIGNING"),
  @SerializedName("SIGNED")
  SIGNED("SIGNED");

  private final String value;

  SigningStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SigningStatus fromValue(String input) {
    for (SigningStatus b : SigningStatus.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<SigningStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final SigningStatus enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public SigningStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SigningStatus.fromValue(value);
    }
  }
}
