/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  * ENVELOPED: Chooses the enveloped transformation format. * XPATH: Chooses the XPath transformation format. * XPATH2_FILTER: Chooses the XPath-2-Filter transformation format.
 */
@JsonAdapter(SignatureTransform.Adapter.class)
public enum SignatureTransform {
  @SerializedName("ENVELOPED")
  ENVELOPED("ENVELOPED"),
  @SerializedName("XPATH")
  XPATH("XPATH"),
  @SerializedName("XPATH2_FILTER")
  XPATH2_FILTER("XPATH2_FILTER");

  private final String value;

  SignatureTransform(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SignatureTransform fromValue(String input) {
    for (SignatureTransform b : SignatureTransform.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<SignatureTransform> {
    @Override
    public void write(final JsonWriter jsonWriter, final SignatureTransform enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public SignatureTransform read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SignatureTransform.fromValue(value);
    }
  }
}
