/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * The signature request configuration.
 */
@Schema(description = "The signature request configuration.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class SignRequestDocument {
  @SerializedName("externalReference")
  private String externalReference = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("documents")
  private List<SignDocumentDocument> documents = new ArrayList<>();

  @SerializedName("preservationInfo")
  private PreservationInfo preservationInfo = null;

  @SerializedName("returnSignedContent")
  private Boolean returnSignedContent = false;

  public SignRequestDocument externalReference(String externalReference) {
    this.externalReference = externalReference;
    return this;
  }

   /**
   * Unique external reference id set by the client service. This should be used to query the document status if an infrastructure error occurs during operation execution that could leave its status incoherent between client and server. A good approach is to have the service client id prefixed to the external reference to avoid collisions with other external references already registered in the system.
   * @return externalReference
  **/
  @Schema(example = "Ext_Ref", requiredMode = Schema.RequiredMode.REQUIRED, description = "Unique external reference id set by the client service. This should be used to query the document status if an infrastructure error occurs during operation execution that could leave its status incoherent between client and server. A good approach is to have the service client id prefixed to the external reference to avoid collisions with other external references already registered in the system.")
  public String getExternalReference() {
    return externalReference;
  }

  public void setExternalReference(String externalReference) {
    this.externalReference = externalReference;
  }

  public SignRequestDocument description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Contextualization of the request. This information will be presented to signers, if applicable.
   * @return description
  **/
  @Schema(example = "Some context.", requiredMode = Schema.RequiredMode.REQUIRED, description = "Contextualization of the request. This information will be presented to signers, if applicable.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SignRequestDocument documents(List<SignDocumentDocument> documents) {
    this.documents = documents;
    return this;
  }

  public SignRequestDocument addDocumentsItem(SignDocumentDocument documentsItem) {
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * Details about the document list to sign.
   * @return documents
  **/
  @Schema( requiredMode = Schema.RequiredMode.REQUIRED, description = "Details about the document list to sign.")
  public List<SignDocumentDocument> getDocuments() {
    return documents;
  }

  public void setDocuments(List<SignDocumentDocument> documents) {
    this.documents = documents;
  }

  public SignRequestDocument preservationInfo(PreservationInfo preservationInfo) {
    this.preservationInfo = preservationInfo;
    return this;
  }

   /**
   * Get preservationInfo
   * @return preservationInfo
  **/
  @Schema()
  public PreservationInfo getPreservationInfo() {
    return preservationInfo;
  }

  public void setPreservationInfo(PreservationInfo preservationInfo) {
    this.preservationInfo = preservationInfo;
  }

  public SignRequestDocument returnSignedContent(Boolean returnSignedContent) {
    this.returnSignedContent = returnSignedContent;
    return this;
  }

   /**
   * States if the signed content (in base64 format) should be returned in the SignOperation response. For better performance should be set as false (no documents content in response), and using the document detail APIs to retrieve the contents.
   * @return returnSignedContent
  **/
  @Schema(example = "false", description = "States if the signed content (in base64 format) should be returned in the SignOperation response. For better performance should be set as false (no documents content in response), and using the document detail APIs to retrieve the contents.")
  public Boolean isReturnSignedContent() {
    return returnSignedContent;
  }

  public void setReturnSignedContent(Boolean returnSignedContent) {
    this.returnSignedContent = returnSignedContent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignRequestDocument signRequestDocument = (SignRequestDocument) o;
    return Objects.equals(this.externalReference, signRequestDocument.externalReference) &&
        Objects.equals(this.description, signRequestDocument.description) &&
        Objects.equals(this.documents, signRequestDocument.documents) &&
        Objects.equals(this.preservationInfo, signRequestDocument.preservationInfo) &&
        Objects.equals(this.returnSignedContent, signRequestDocument.returnSignedContent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalReference, description, documents, preservationInfo, returnSignedContent);
  }


  @Override
  public String toString() {

      return "class SignRequestDocument {\n" +
              "    externalReference: " + toIndentedString(externalReference) + "\n" +
              "    description: " + toIndentedString(description) + "\n" +
              "    documents: " + toIndentedString(documents) + "\n" +
              "    preservationInfo: " + toIndentedString(preservationInfo) + "\n" +
              "    returnSignedContent: " + toIndentedString(returnSignedContent) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
