/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Details about the sign document for sign.
 */
@Schema(description = "Details about the sign document for sign.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class SignDocumentBase64Document {
  @SerializedName("documentRequest")
  private Base64Document documentRequest = null;

  @SerializedName("signatureInfo")
  private SignatureInfo signatureInfo = null;

  public SignDocumentBase64Document documentRequest(Base64Document documentRequest) {
    this.documentRequest = documentRequest;
    return this;
  }

   /**
   * Get documentRequest
   * @return documentRequest
  **/
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
  public Base64Document getDocumentRequest() {
    return documentRequest;
  }

  public void setDocumentRequest(Base64Document documentRequest) {
    this.documentRequest = documentRequest;
  }

  public SignDocumentBase64Document signatureInfo(SignatureInfo signatureInfo) {
    this.signatureInfo = signatureInfo;
    return this;
  }

   /**
   * Get signatureInfo
   * @return signatureInfo
  **/
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
  public SignatureInfo getSignatureInfo() {
    return signatureInfo;
  }

  public void setSignatureInfo(SignatureInfo signatureInfo) {
    this.signatureInfo = signatureInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignDocumentBase64Document signDocumentBase64Document = (SignDocumentBase64Document) o;
    return Objects.equals(this.documentRequest, signDocumentBase64Document.documentRequest) &&
        Objects.equals(this.signatureInfo, signDocumentBase64Document.signatureInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentRequest, signatureInfo);
  }


  @Override
  public String toString() {

      return "class SignDocumentBase64Document {\n" +
              "    documentRequest: " + toIndentedString(documentRequest) + "\n" +
              "    signatureInfo: " + toIndentedString(signatureInfo) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
