/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * Information about a signature operation.
 */
@Schema(description = "Information about a signature operation.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")

public class SignOperation {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("type")
  private OperationType type = null;

  @SerializedName("status")
  private OperationStatus status = null;

  @SerializedName("issuerCompany")
  private Company issuerCompany = null;

  @SerializedName("issuerClientServiceAlias")
  private String issuerClientServiceAlias = null;

  @SerializedName("creationDate")
  private OffsetDateTime creationDate = null;

  @SerializedName("folderExternalReference")
  private String folderExternalReference = null;

  @SerializedName("signatureQueuePriority")
  private SignatureQueuePriority signatureQueuePriority = null;

  @SerializedName("folder")
  private Folder folder = null;

  @SerializedName("documentList")
  private List<DocumentResponse> documentList = null;

  @SerializedName("deliveryInfo")
  private DeliveryInfo deliveryInfo = null;

  @SerializedName("executionTime")
  private Integer executionTime = null;

  public SignOperation id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Operation unique id.
   * @return id
  **/
  @Schema(example = "123", requiredMode = Schema.RequiredMode.REQUIRED, description = "Operation unique id.")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SignOperation type(OperationType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema()
  public OperationType getType() {
    return type;
  }

  public void setType(OperationType type) {
    this.type = type;
  }

  public SignOperation status(OperationStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema()
  public OperationStatus getStatus() {
    return status;
  }

  public void setStatus(OperationStatus status) {
    this.status = status;
  }

  public SignOperation issuerCompany(Company issuerCompany) {
    this.issuerCompany = issuerCompany;
    return this;
  }

   /**
   * Get issuerCompany
   * @return issuerCompany
  **/
  @Schema(description = "")
  public Company getIssuerCompany() {
    return issuerCompany;
  }

  public void setIssuerCompany(Company issuerCompany) {
    this.issuerCompany = issuerCompany;
  }

  public SignOperation issuerClientServiceAlias(String issuerClientServiceAlias) {
    this.issuerClientServiceAlias = issuerClientServiceAlias;
    return this;
  }

   /**
   * Issuer client service that created the operation.
   * @return issuerClientServiceAlias
  **/
  @Schema(description = "Issuer client service that created the operation.")
  public String getIssuerClientServiceAlias() {
    return issuerClientServiceAlias;
  }

  public void setIssuerClientServiceAlias(String issuerClientServiceAlias) {
    this.issuerClientServiceAlias = issuerClientServiceAlias;
  }

  public SignOperation creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Operation registry date.
   * @return creationDate
  **/
  @Schema(description = "Operation registry date.")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public SignOperation folderExternalReference(String folderExternalReference) {
    this.folderExternalReference = folderExternalReference;
    return this;
  }

   /**
   * Folder external reference.
   * @return folderExternalReference
  **/
  @Schema(description = "Folder external reference.")
  public String getFolderExternalReference() {
    return folderExternalReference;
  }

  public void setFolderExternalReference(String folderExternalReference) {
    this.folderExternalReference = folderExternalReference;
  }

  public SignOperation signatureQueuePriority(SignatureQueuePriority signatureQueuePriority) {
    this.signatureQueuePriority = signatureQueuePriority;
    return this;
  }

   /**
   * Get signatureQueuePriority
   * @return signatureQueuePriority
  **/
  @Schema()
  public SignatureQueuePriority getSignatureQueuePriority() {
    return signatureQueuePriority;
  }

  public void setSignatureQueuePriority(SignatureQueuePriority signatureQueuePriority) {
    this.signatureQueuePriority = signatureQueuePriority;
  }

  public SignOperation folder(Folder folder) {
    this.folder = folder;
    return this;
  }

   /**
   * Get folder
   * @return folder
  **/
  @Schema()
  public Folder getFolder() {
    return folder;
  }

  public void setFolder(Folder folder) {
    this.folder = folder;
  }

  public SignOperation documentList(List<DocumentResponse> documentList) {
    this.documentList = documentList;
    return this;
  }

  public SignOperation addDocumentListItem(DocumentResponse documentListItem) {
    if (this.documentList == null) {
      this.documentList = new ArrayList<>();
    }
    this.documentList.add(documentListItem);
    return this;
  }

   /**
   * List of documents of the operation and aggregated in the defined folder.
   * @return documentList
  **/
  @Schema(description = "List of documents of the operation and aggregated in the defined folder.")
  public List<DocumentResponse> getDocumentList() {
    return documentList;
  }

  public void setDocumentList(List<DocumentResponse> documentList) {
    this.documentList = documentList;
  }

  public SignOperation deliveryInfo(DeliveryInfo deliveryInfo) {
    this.deliveryInfo = deliveryInfo;
    return this;
  }

   /**
   * Get deliveryInfo
   * @return deliveryInfo
  **/
  @Schema()
  public DeliveryInfo getDeliveryInfo() {
    return deliveryInfo;
  }

  public void setDeliveryInfo(DeliveryInfo deliveryInfo) {
    this.deliveryInfo = deliveryInfo;
  }

  public SignOperation executionTime(Integer executionTime) {
    this.executionTime = executionTime;
    return this;
  }

   /**
   * Operation execution time (in milliseconds).
   * @return executionTime
  **/
  @Schema(example = "10000", description = "Operation execution time (in milliseconds).")
  public Integer getExecutionTime() {
    return executionTime;
  }

  public void setExecutionTime(Integer executionTime) {
    this.executionTime = executionTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignOperation signOperation = (SignOperation) o;
    return Objects.equals(this.id, signOperation.id) &&
        Objects.equals(this.type, signOperation.type) &&
        Objects.equals(this.status, signOperation.status) &&
        Objects.equals(this.issuerCompany, signOperation.issuerCompany) &&
        Objects.equals(this.issuerClientServiceAlias, signOperation.issuerClientServiceAlias) &&
        Objects.equals(this.creationDate, signOperation.creationDate) &&
        Objects.equals(this.folderExternalReference, signOperation.folderExternalReference) &&
        Objects.equals(this.signatureQueuePriority, signOperation.signatureQueuePriority) &&
        Objects.equals(this.folder, signOperation.folder) &&
        Objects.equals(this.documentList, signOperation.documentList) &&
        Objects.equals(this.deliveryInfo, signOperation.deliveryInfo) &&
        Objects.equals(this.executionTime, signOperation.executionTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, type, status, issuerCompany, issuerClientServiceAlias, creationDate, folderExternalReference, signatureQueuePriority, folder, documentList, deliveryInfo, executionTime);
  }


  @Override
  public String toString() {

      return "class SignOperation {\n" +
              "    id: " + toIndentedString(id) + "\n" +
              "    type: " + toIndentedString(type) + "\n" +
              "    status: " + toIndentedString(status) + "\n" +
              "    issuerCompany: " + toIndentedString(issuerCompany) + "\n" +
              "    issuerClientServiceAlias: " + toIndentedString(issuerClientServiceAlias) + "\n" +
              "    creationDate: " + toIndentedString(creationDate) + "\n" +
              "    folderExternalReference: " + toIndentedString(folderExternalReference) + "\n" +
              "    signatureQueuePriority: " + toIndentedString(signatureQueuePriority) + "\n" +
              "    folder: " + toIndentedString(folder) + "\n" +
              "    documentList: " + toIndentedString(documentList) + "\n" +
              "    deliveryInfo: " + toIndentedString(deliveryInfo) + "\n" +
              "    executionTime: " + toIndentedString(executionTime) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
