/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  * INVALID_CERT_SERVICE_CREDS: Certificate service access credentials invalid or expired. * INVALID_CERT_ACCESS_ACCOUNT: Invalid certificate access account when trying to invoke the certificate service. * CERT_SERVICE_GLOBAL_ERROR: Generic error accessing the certificate service. * CONFIGURATION_SIGN_ERROR: Signature requet contains configuration errors. * TIMESTAMP_SIGN_ERROR: Error accessing the timestamping service. * INVALID_CERTIFICATE_SIGN_ERROR: Error using the signing certificate. * STORAGE_SERVICE_GLOBAL_ERROR: Error storing the signed document. * SIGN_OPERATION_INTERNAL_ERROR: Internal error in the signature operation.
 */
@JsonAdapter(SigningError.Adapter.class)
public enum SigningError {
  @SerializedName("INVALID_CERT_SERVICE_CREDS")
  INVALID_CERT_SERVICE_CREDS("INVALID_CERT_SERVICE_CREDS"),
  @SerializedName("INVALID_CERT_ACCESS_ACCOUNT")
  INVALID_CERT_ACCESS_ACCOUNT("INVALID_CERT_ACCESS_ACCOUNT"),
  @SerializedName("CERT_SERVICE_GLOBAL_ERROR")
  CERT_SERVICE_GLOBAL_ERROR("CERT_SERVICE_GLOBAL_ERROR"),
  @SerializedName("CONFIGURATION_SIGN_ERROR")
  CONFIGURATION_SIGN_ERROR("CONFIGURATION_SIGN_ERROR"),
  @SerializedName("TIMESTAMP_SIGN_ERROR")
  TIMESTAMP_SIGN_ERROR("TIMESTAMP_SIGN_ERROR"),
  @SerializedName("INVALID_CERTIFICATE_SIGN_ERROR")
  INVALID_CERTIFICATE_SIGN_ERROR("INVALID_CERTIFICATE_SIGN_ERROR"),
  @SerializedName("STORAGE_SERVICE_GLOBAL_ERROR")
  STORAGE_SERVICE_GLOBAL_ERROR("STORAGE_SERVICE_GLOBAL_ERROR"),
  @SerializedName("SIGN_OPERATION_INTERNAL_ERROR")
  SIGN_OPERATION_INTERNAL_ERROR("SIGN_OPERATION_INTERNAL_ERROR");

  private final String value;

  SigningError(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SigningError fromValue(String input) {
    for (SigningError b : SigningError.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<SigningError> {
    @Override
    public void write(final JsonWriter jsonWriter, final SigningError enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public SigningError read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SigningError.fromValue(value);
    }
  }
}
