/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.beans.factory.config.BeanDefinition;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.io.IOException;
/**
 * Signature information to be applied to a document.
 */
@Schema(description = "Signature information to be applied to a document.")
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-10T10:19:21.648339263Z[Europe/Lisbon]")
@Component
@Scope(value = BeanDefinition.SCOPE_PROTOTYPE)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonFormat(with = JsonFormat.Feature.ACCEPT_CASE_INSENSITIVE_PROPERTIES)
public class SignatureInfo {
  /**
   *  * PAdES: Usually applied to PDF files. * XAdES: Usually applied to XML text files. * CAdES: Usually applied to binary files.
   */
  @JsonAdapter(SignatureTypeEnum.Adapter.class)
  public enum SignatureTypeEnum {
    @SerializedName("PAdES")
    PADES("PAdES"),
    @SerializedName("XAdES")
    XADES("XAdES"),
    @SerializedName("CAdES")
    CADES("CAdES");

    private final String value;

    SignatureTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static SignatureTypeEnum fromValue(String input) {
      for (SignatureTypeEnum b : SignatureTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<SignatureTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SignatureTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public SignatureTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return SignatureTypeEnum.fromValue(value);
      }
    }
  }  @SerializedName("signatureType")
  private SignatureTypeEnum signatureType = null;

  @SerializedName("visibleSignatureInfo")
  private VisibleSignatureInfo visibleSignatureInfo = null;

  @SerializedName("reason")
  private String reason = null;

  @SerializedName("location")
  private String location = null;

  @SerializedName("applyTimestamp")
  private Boolean applyTimestamp = false;

  @SerializedName("advancedSignatureInfo")
  private AdvancedSignatureInfo advancedSignatureInfo = null;

  public SignatureInfo signatureType(SignatureTypeEnum signatureType) {
    this.signatureType = signatureType;
    return this;
  }

   /**
   *  * PAdES: Usually applied to PDF files. * XAdES: Usually applied to XML text files. * CAdES: Usually applied to binary files.
   * @return signatureType
  **/
  @Schema(example = "PAdES", requiredMode = Schema.RequiredMode.REQUIRED, description = " * PAdES: Usually applied to PDF files. * XAdES: Usually applied to XML text files. * CAdES: Usually applied to binary files.")
  public SignatureTypeEnum getSignatureType() {
    return signatureType;
  }

  public void setSignatureType(SignatureTypeEnum signatureType) {
    this.signatureType = signatureType;
  }

  public SignatureInfo visibleSignatureInfo(VisibleSignatureInfo visibleSignatureInfo) {
    this.visibleSignatureInfo = visibleSignatureInfo;
    return this;
  }

   /**
   * Get visibleSignatureInfo
   * @return visibleSignatureInfo
  **/
  @Schema()
  public VisibleSignatureInfo getVisibleSignatureInfo() {
    return visibleSignatureInfo;
  }

  public void setVisibleSignatureInfo(VisibleSignatureInfo visibleSignatureInfo) {
    this.visibleSignatureInfo = visibleSignatureInfo;
  }

  public SignatureInfo reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Signature reason (free text) to be set on document metadata.Support is restricted to PAdES based signature types.
   * @return reason
  **/
  @Schema(example = "Test API reason", description = "Signature reason (free text) to be set on document metadata.Support is restricted to PAdES based signature types.")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public SignatureInfo location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Signature location (free text) to be set on document metadata.Support is restricted to PAdES based signature types.
   * @return location
  **/
  @Schema(example = "Test API location", description = "Signature location (free text) to be set on document metadata.Support is restricted to PAdES based signature types.")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public SignatureInfo applyTimestamp(Boolean applyTimestamp) {
    this.applyTimestamp = applyTimestamp;
    return this;
  }

   /**
   * Will apply timestamp to signature. Will use the default system timestamp server.
   * @return applyTimestamp
  **/
  @Schema(example = "true", description = "Will apply timestamp to signature. Will use the default system timestamp server.")
  public Boolean isApplyTimestamp() {
    return applyTimestamp;
  }

  public void setApplyTimestamp(Boolean applyTimestamp) {
    this.applyTimestamp = applyTimestamp;
  }

  public SignatureInfo advancedSignatureInfo(AdvancedSignatureInfo advancedSignatureInfo) {
    this.advancedSignatureInfo = advancedSignatureInfo;
    return this;
  }

   /**
   * Get advancedSignatureInfo
   * @return advancedSignatureInfo
  **/
  @Schema()
  public AdvancedSignatureInfo getAdvancedSignatureInfo() {
    return advancedSignatureInfo;
  }

  public void setAdvancedSignatureInfo(AdvancedSignatureInfo advancedSignatureInfo) {
    this.advancedSignatureInfo = advancedSignatureInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SignatureInfo signatureInfo = (SignatureInfo) o;
    return Objects.equals(this.signatureType, signatureInfo.signatureType) &&
        Objects.equals(this.visibleSignatureInfo, signatureInfo.visibleSignatureInfo) &&
        Objects.equals(this.reason, signatureInfo.reason) &&
        Objects.equals(this.location, signatureInfo.location) &&
        Objects.equals(this.applyTimestamp, signatureInfo.applyTimestamp) &&
        Objects.equals(this.advancedSignatureInfo, signatureInfo.advancedSignatureInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signatureType, visibleSignatureInfo, reason, location, applyTimestamp, advancedSignatureInfo);
  }


  @Override
  public String toString() {

      return "class SignatureInfo {\n" +
              "    signatureType: " + toIndentedString(signatureType) + "\n" +
              "    visibleSignatureInfo: " + toIndentedString(visibleSignatureInfo) + "\n" +
              "    reason: " + toIndentedString(reason) + "\n" +
              "    location: " + toIndentedString(location) + "\n" +
              "    applyTimestamp: " + toIndentedString(applyTimestamp) + "\n" +
              "    advancedSignatureInfo: " + toIndentedString(advancedSignatureInfo) + "\n" +
              "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
