/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  * CONTENT_PRESERVED: File content is set to be preserved (actions will be taken to ensure its integrity). * CONTENT_STORED: File content is set to be stored, but not to be preserved. * CONTENT_NOT_STORED: File content is not present (only metadata). * DELETED: File and all metadata are marked for physical deletion from database.
 */
@JsonAdapter(StorageStatus.Adapter.class)
public enum StorageStatus {
  @SerializedName("CONTENT_PRESERVED")
  CONTENT_PRESERVED("CONTENT_PRESERVED"),
  @SerializedName("CONTENT_STORED")
  CONTENT_STORED("CONTENT_STORED"),
  @SerializedName("CONTENT_NOT_STORED")
  CONTENT_NOT_STORED("CONTENT_NOT_STORED"),
  @SerializedName("DELETED")
  DELETED("DELETED");

  private final String value;

  StorageStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static StorageStatus fromValue(String input) {
    for (StorageStatus b : StorageStatus.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<StorageStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final StorageStatus enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public StorageStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return StorageStatus.fromValue(value);
    }
  }
}
