/*
 * SignStash Integration REST API
 * To test the API please select the option \"Authorize\" and paste the JWT token received on a successful OAuth authentication: <b><JWT_Token></b>  After executing the authorization you can proceed to try out any of the methods in this API.
 *
 * OpenAPI spec version: v0
 * Contact: signstash@multicert.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package pt.pchouse.pdf.api.sign.multicert.model;

import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 *  * IMAGE_PNG: Image type set to visible signatures. Supported of png image in the format Base64. * IMAGE_JPG: Image type set to visible signatures. Supported of jpg image in the format Base64.
 */
@JsonAdapter(VisibleImageType.Adapter.class)
public enum VisibleImageType {
  @SerializedName("IMAGE_PNG")
  PNG("IMAGE_PNG"),
  @SerializedName("IMAGE_JPG")
  JPG("IMAGE_JPG");

  private final String value;

  VisibleImageType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static VisibleImageType fromValue(String input) {
    for (VisibleImageType b : VisibleImageType.values()) {
      if (b.value.equals(input)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<VisibleImageType> {
    @Override
    public void write(final JsonWriter jsonWriter, final VisibleImageType enumeration) throws IOException {
      jsonWriter.value(String.valueOf(enumeration.getValue()));
    }

    @Override
    public VisibleImageType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return VisibleImageType.fromValue(value);
    }
  }
}
